trigger:
- main

pool:
  name: PythonDemoPool

steps:

- script: |
    D:\Python312New\python.exe --version
    D:\Python312New\python.exe -m pip --version
  displayName: 'Verify Python 3.12'

- script: |
    D:\Python312New\python.exe -m pip install --upgrade pip
    D:\Python312New\python.exe -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    D:\Python312New\python.exe -m pytest
  displayName: 'Run unit tests'